apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins
rules:
- apiGroups: ["*"]
  resources:
  - statefulsets
  - services
  - replicasets
  - pods
  - pods/log
  - pods/exec
  - jobs
  - configmaps
  - secrets
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - namespaces
  - events
  verbs: ["create", "get", "watch", "delete", "list", "patch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default
